# Generated by Django 3.2.6 on 2023-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobdescription_jobdescriptionchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
