# Generated by Django 3.2.6 on 2023-09-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_jobdescription_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptionchunk',
            name='token_count',
            field=models.IntegerField(null=True),
        ),
    ]
