#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

[ -d "/app/client/dist" ] && python3 server/manage.py collectstatic --noinput || echo "Client Folder not built skipping collect static"

python3 server/manage.py migrate
python3 server/manage.py runserver 0.0.0.0:8000
